// <auto-generated />
using System;
using AntecipacaoRecebivel.Infrastructure.DataAcess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntecipacaoRecebivel.Infrastructure.Migrations
{
    [DbContext(typeof(AntecipacaoRecebiveisDbContext))]
    [Migration("20241024162331_CriacaoBanco")]
    partial class CriacaoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualiza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimiteDeCreditoDisponivel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("CARRINHO", (string)null);
                });

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataAtualiza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ramo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualiza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("NOTAFISCAL", (string)null);
                });

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.Carrinho", b =>
                {
                    b.HasOne("AntecipacaoRecebivel.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Carrinhos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.NotaFiscal", b =>
                {
                    b.HasOne("AntecipacaoRecebivel.Domain.Entities.Carrinho", "Carrinho")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AntecipacaoRecebivel.Domain.Entities.Empresa", "Empresa")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.Carrinho", b =>
                {
                    b.Navigation("NotasFiscais");
                });

            modelBuilder.Entity("AntecipacaoRecebivel.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
