// <auto-generated />
using System;
using AnticipationOfReceivables.Infrastructure.DataAcess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnticipationOfReceivables.Infrastructure.Migrations
{
    [DbContext(typeof(AnticipationOfReceivablesDbContext))]
    [Migration("20251209035630_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AnticipationOfReceivables")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Cart", "AnticipationOfReceivables");
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessSector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Company", "AnticipationOfReceivables");
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Invoices", "AnticipationOfReceivables");
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Cart", b =>
                {
                    b.HasOne("AnticipationOfReceivables.Domain.Entities.Company", "Company")
                        .WithMany("Carts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Money", "AvailableCreditLimit", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AvailableCreditLimit");

                            b1.HasKey("CartId");

                            b1.ToTable("Cart", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Money", "GrossTotalAmount", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("GrossTotalAmount");

                            b1.HasKey("CartId");

                            b1.ToTable("Cart", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Money", "NetTotalAmount", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("NetTotalAmount");

                            b1.HasKey("CartId");

                            b1.ToTable("Cart", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.Navigation("AvailableCreditLimit")
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("GrossTotalAmount")
                        .IsRequired();

                    b.Navigation("NetTotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Company", b =>
                {
                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("Cnpj");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Company", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CreditLimit");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Company", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Money", "Revenue", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Revenue");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Company", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("CreditLimit")
                        .IsRequired();

                    b.Navigation("Revenue")
                        .IsRequired();
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("AnticipationOfReceivables.Domain.Entities.Cart", "Cart")
                        .WithMany("Invoices")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AnticipationOfReceivables.Domain.Entities.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.DueDate", "DueDate", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DueDate");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.InvoiceNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Number");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("AnticipationOfReceivables.BuildingBlocks.Domain.ValueObjects.Money", "GrossAmount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("GrossAmount");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices", "AnticipationOfReceivables");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Cart");

                    b.Navigation("Company");

                    b.Navigation("DueDate")
                        .IsRequired();

                    b.Navigation("GrossAmount")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("AnticipationOfReceivables.Domain.Entities.Company", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
